export {
  AboutMeCard,
  AnimatedCards,
  ButtonsAboutUs,
  EducationCard,
  FloatingCards,
  Line,
  List,
  Logo,
  MenuIcon,
  NavigationButton,
  PaginationButtons,
  ProfessionalExperienceCard,
  QrCode,
  RecipeCard,
  SideCard,
  SideMenu,
  SocialIcons,
  SoftwaresCard,
  TextMain,
} from "@/ui/ui";
